# Generated by Django 2.0 on 2019-05-30 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=32)),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gunit', models.CharField(max_length=32)),
                ('gstock', models.IntegerField()),
                ('gsummary', models.CharField(max_length=100)),
                ('gdetail', models.CharField(max_length=200)),
                ('gclick', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtype', models.CharField(max_length=32)),
                ('is_delete', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsType'),
        ),
    ]
