# Generated by Django 2.0 on 2019-05-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(default='', upload_to='images/df_goods'),
        ),
    ]
